#pragma once
//Automatically generated build count file. DO NOT EDIT MANUALLY!

#define BUILD_COUNT_ANUBIS 91
#define BUILD_COUNT_DESKTOP_EDTCHAL 2756

#define RELEASE_COUNT_ANUBIS 0
#define RELEASE_COUNT_DESKTOP_EDTCHAL 50

#define BUILDCOUNT (BUILD_COUNT_ANUBIS+BUILD_COUNT_DESKTOP_EDTCHAL)
#define RELEASECOUNT (RELEASE_COUNT_ANUBIS+RELEASE_COUNT_DESKTOP_EDTCHAL)
